nextcloud-libraries/eslint-config

index.js, package.json
From https://github.com/skjnldsv/vueexample/blob/master/.eslintrc.js
See working example https://github.com/skjnldsv/vueexample/pull/249
=> Create first config

index.js
These globals are already defined in the environment `nextcloud` which is loaded by extending the config `plugin:nextcloud/recommended`.
=> remove globals

index.js
Some improvements, I have made a comment for every change.
I like also the following rules:
```js
// always add a trailing comma (for diff readability)
'comma-dangle': ['warn', 'always-multiline'],
// html ending tag on newline if tag is multiline (for diff readability)
'vue/html-closing-bracket-newline': ['error', { multiline: 'always' }],
```
But if this is not wanted, I will use it in my local config, only.
=> consolidate config

index.js
This is needed for proper alignment of comments in CSS code embedded in Vue files. For example:
```
-->/* Here starts a long comment that would be too long to have in a
--> * single line so is continued in the next one. */
```
Otherwise [it would need to be written](https://github.com/nextcloud/spreed/blob/eb7aa7b4938a9d16ab96815bc314dbe92cd5a850/src/FilesSidebarTabApp.vue#L309-L310) as
```
-->/* Here starts a long comment that would be too long to have in a
-->* single line so is continued in the next one. */
```
to prevent the linter from complaining.
See https://eslint.org/docs/rules/no-mixed-spaces-and-tabs#smart-tabs
**Important:** this change is needed only for the CSS code; the JavaScript code in Vue files already allows tabs followed by spaces for alignment, but I do not know why …
=> Allow spaces after tabs for alignment

index.js, package-lock.json, package.json
`eslint-plugin-nextcloud` was renamed to `@nextcloud/eslint-plugin`. At some point in the future, this package could also be renamed ...
=> switch to @nextcloud/eslint-plugin

index.js
This PR adds the object-shorthand syntax rule. I also took the liberty to change the double-quotes to single-quotes for the last rule.
Closes #35.
=> Add object-shorthand rule

index.js, package-lock.json, package.json
The package `babel-eslint` is deprecated and we should replace it with `@babel/eslint-parser`.
Can lead to issues like https://github.com/nextcloud/mail/pull/4702#issuecomment-793636549.
=> Replace babel-eslint with @babel/eslint-parser

package-lock.json, package.json
=> remove eslint-plugin-standard

index.js
Updates `space-before-function-paren` rule to require a space before async arrow function parentheses as described in the [docs](https://eslint.org/docs/rules/space-before-function-paren#options)
=> Require a space before async arrow function parentheses

index.js
```js
/**
* @copyright Copyright (c) 2019 John Molakvoæ <skjnldsv@protonmail.com>
* @author John Molakvoæ <skjnldsv@protonmail.com>
* @license AGPL-3.0-or-later
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see …
```
=> Fix license header tags spacing

index.js
Introduced with latest `@nextcloud/eslint-config@7.0.0`. Fixing this regression
Ref: https://github.com/nextcloud/viewer/pull/1131
=> Allow component names to be single-word

index.js
Sorry for the regression.
Here is the fix (from 7.0.1 to this PR)
Ref: https://github.com/nextcloud/server/pull/30729
=> Fix usual same-line vue attribute behaviour

index.js
Warn when file extensions are not used on imports paths with the [import/extensions rule](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/extensions.md), this is to stay up-to-date with the ecosystem e.g. [Node.js 14 docs](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_mandatory_file_extensions)
In future we may want to set this to `error`
Also see https://github.com/nextcloud/webpack-vue-config/pull/297
=> Add import extension rule

index.js
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Also update `eslint-config-n` custom rules

index.js
Allow usage of TypeScript syntax e.g.
```js
/**
* @type {import('vue').Component}
*/
const component = new Vue()
```
Documentation https://github.com/gajus/eslint-plugin-jsdoc/blob/v39.2.1/README.md#mode
=> Allow TypeScript syntax in JSDoc comments

.github/workflows/lint.yml, README.md, index.js, package.json
Enforce our coding style also on this project by using the config for linting itself.
Also fixed the issues found by eslint.
And with the second commit I fixed the broken "build state" as there is no travis on this project anymore.
=> feat: Add scripts for linting the config and fixed issues found

index.js, package-lock.json, package.json
This adds a sub-config for typescript projects, e.g. we could use it within our libraries or for users which use TypeScript for app development (vue + ts is pretty common nowadays).
=> feat: Add sub config for TypeScript projects

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud/eslint-config/compare/v8.2.0...v8.2.1)
**Fixed:**
- Fix resolving packages that use the package `exports` feature by @susnux in https://github.com/nextcloud/eslint-config/pull/452
**Merged pull requests:**
- Various dependencies upgrades
=> release: 8.2.1

.github/workflows/node.yml, index.js, package-lock.json, package.json, tests/eslint-config.test.ts, tests/eslint.d.ts, tests/fixtures/example-fail.js, tests/fixtures/some.tsx, tests/setup-jest.ts
* Resolves: #181 
Notices that tsx files are not supported on the groupfolders app, so added tsx support.
And to test that is actually works I added a test case (so this implements #181 ).
=> Adding tests and allow linting TSX files

index.js, tests/eslint-config.test.ts, tests/fixtures/webpack-nonce.js
```
// eslint-disable-next-line camelcase
__webpack_nonce__ = 'foobar'
// eslint-disable-next-line camelcase
__webpack_public_path__ = 'foobar'
```
Motivation: `__webpack_nonce__` will always violate the camelcase rule. 
The error is usually ignored with `// eslint-disable-next-line camelcase`. 
It sounds reasonable to me to add the ignore rule by default. 
An alternative approach could be to define `__webpack_nonce__` as globals. The advantage is that also the un-def violation is gone and globals are by default excluded from the camelcase rule. But it's weird to define `__webpack_nonce` as global for every app using eslint when the variable is only available when bundled with webpack.
=> feat: ignore camelcase rule for __webpack variables

package-lock.json, package.json
We have dropped the eslint webpack plugin some time ago, so we should also drop the webpack dependency.
=> Drop webpack dependency

CHANGELOG.md, README.md, index.js, package-lock.json, package.json, parts/base.js, parts/typescript.js, parts/vue.js, tests/eslint-config.test.ts, tests/eslint-typescript-config.test.ts, tests/fixtures/composition-test.vue, tests/fixtures/typescript-test.vue, typescript.js
* Resolves: #559 
1. Splits the config into 3 parts for better readability
2. Support Composition API (`<script setup>`) by using `vue-eslint-parser` for vue files
3. Add a second config for projects using vue files with Typescript (`<script lang="ts">`)
=> Support Composition API & Typescript + Vue projects

parts/typescript.js
Valid Typescript file extensions are:
* `.ts`
* `.mts` (es module Typescript)
* `.cts` (commonjs Typescript)
* `.tsx`
=> fix: Add Typescript overrides for all valid Typescript file extensions

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud/eslint-config/compare/v8.3.0-beta.0...v8.3.0-beta.1)
**Features:**
- Provide config for vue files written in Typescript, use `extends: "@nextcloud/eslint-config/typescript"`.
- Fully support vue files using the Composition API `<script setup>`.
=> v8.3.0-beta.1

CHANGELOG.md, parts/typescript.js
=> fix: allow empty functions

package.json, parts/base.js, parts/typescript.js, parts/vue.js
Also allows your IDE to take the eslint config for linting the project while developing.
Also run the linter and fix the issues.
=> Make eslint to take this config for linting the config

parts/typescript.js
Allow e.g. this for vue `<script setup>`:
```ts
const emit = defineEmits<{
foo: number
}>()
```
=> fix(typescript): Allow generic type parameters on function calls

parts/base.js, parts/typescript.js
Many of your projects use `@jest-environment` inside tests, so we should allow that docblock.
=> fix: Allow `@jest-environment` docblock for jest tests

typescript.js
Solving `import/no-unresolved` when using `<script lang="ts">` and importing Typescript files.
=> fix(typescript): Also set the typescript settings to the vue overrides for typescript import resolving

README.md, parts/vue3.js, vue3.js
This adds a new `vue3` sub-configuration so we can support vue 2 and vue 3 with this linter config.
=> feat: Add `vue3` sub-configuration to allow linting Vue 3 projects

parts/vue3.js
While I totally agree with the rules, they are much different from our rules for Vue 2 requiring having many formatting changes and even filenames between Vue 2 and Vue 3 apps. It makes diffs and backports complicated during migration period.
=> fix(vue3): align rules with Vue 2 rules

parts/vue3.js
=> fix(vue3): config crashes ESLint

CHANGELOG.md, package-lock.json, package.json
[Full Changelog](https://github.com/nextcloud-libraries/eslint-config/compare/v8.4.0...v8.4.1)
* fix(vue3): align rules with Vue 2 rules by @ShGKme in https://github.com/nextcloud-libraries/eslint-config/pull/771
* fix(vue3): config crashes ESLint by @ShGKme in https://github.com/nextcloud-libraries/eslint-config/pull/770
* build(deps-dev): Bump eslint-plugin-jsdoc from 48.2.4 to 48.2.5 by @dependabot in https://github.com/nextcloud-libraries/eslint-config/pull/769
=> release: v8.4.1

.git-blame-ignore-revs
* 96662f1 contains whitespace changes only.
This file will be picked up automatically by github.
Instructions for configuring git locally are included in
`.git-blame-ignore-revs` file.
=> enh(git): ignore formatting commits in git blame

parts/typescript.js
Same as `jsdoc/require-param-type`
=> fix(typescript): do not require returns type in jsdoc

CHANGELOG.md, package-lock.json, package.json
* fix(typescript): do not require returns type in jsdoc by @ShGKme in https://github.com/nextcloud-libraries/eslint-config/pull/857
* Updated development dependencies
* Add SPDX header  by @AndyScherzinger in https://github.com/nextcloud-libraries/eslint-config/pull/802
* enh(git): ignore formatting commits in git blame by @max-nextcloud in https://github.com/nextcloud-libraries/eslint-config/pull/854
=> chore: prepare v8.4.2

lib/configs/codeStyle.ts, tests/fixtures/codestyle/input/arrow-function.ts, tests/fixtures/codestyle/input/function.ts, tests/fixtures/codestyle/output/arrow-function.ts, tests/fixtures/codestyle/output/function.ts
As per code style: https://docs.nextcloud.com/server/latest/developer_manual/getting_started/coding_standards/javascript.html#code-style
Good:
- `function foo() {}`
- `function() {}`
- `foo()`
Bad:
- `function foo () {}`
- `function () {}`
- `foo ()`
=> fix(codestyle): Enforce no space before function parenthesis

lib/configs/codeStyle.ts
* Issue of https://github.com/nextcloud-libraries/eslint-config/pull/902
The `flat` option is now always enabled and does not exist anymore.
=> fix(codeStyle): Adjust `stylistic` rules config

lib/configs/typescript.ts, tests/config-typescript.test.ts, tests/fixtures/use-before-define.ts
This allows to write code in reading order - perfectly fine from syntax as `function` will be defined before executing the file anyways.
=> fix(typescript): allow to use function before definition

lib/configs/codeStyle.ts, lib/plugins/l10n/index.ts, lib/plugins/l10n/rules/enforce-ellipsis.test.ts, lib/plugins/l10n/rules/enforce-ellipsis.ts, lib/plugins/l10n/rules/non-breaking-space.test.ts, lib/plugins/l10n/rules/non-breaking-space.ts
* Resolves #9 
1. Enforce ellipsis instead of tipple dots for translations
2. Enforce non breaking spaces instead of normal spaces before ellipsis
=> feat: enforce non-breaking spaces before ellipsis for translations

README.md
use tabs consistent for code examples.
=> docs: consistent tab usage in readme

lib/configs/codeStyle.ts, lib/configs/vue.ts
- Vue shall have empty lines between blocks
- Do not enforce array elements on empty lines but be consistent
=> fix(codestyle): adjust empty lines style

lib/configs/javascript.ts, tests/config-javascript.test.ts
`function`, similar as `var`, are special ECMAscript. They will be defined at any position in the script even if they are defined after usage.
=> fix(javascript): allow using functions before they are defined

lib/globs.ts
While testing the configurations in some apps I noticed JSdoc rules are not properly disabled in test files.
Adjusting the glob did help.
=> fix(globs): properly ignore test files

eslint.config.ts, lib/configs/documentation.ts, lib/plugins/nextcloud/rules/no-removed-apis.ts, package.json, tsconfig.json
Just bump our development version of node to 22.10+ so we can directly use Typescript as the configuration format.
=> chore: allow to run `npm lint` without compile step

package.json
Node <20.19 results in an error between in vue-eslint-plugin from stylistic resolving.
=> fix: require node ^20.19

lib/configs/vue.ts
It isn't very useful in fully migrated to TS repositories but adds too much noise in non-migrated
=> fix(vue): allow JS Vue files

lib/configs/codeStyle.ts, tests/fixtures/codestyle/input/array.js, tests/fixtures/codestyle/output/array.js
- Fix: https://github.com/nextcloud-libraries/eslint-config/issues/979
- Same as https://github.com/nextcloud-libraries/eslint-config/pull/996
Allow developers to decide when a single-line array is fine.
=> fix(codeStyle): allow single line arrays

lib/configs/typescript.ts
- Fix: https://github.com/nextcloud-libraries/eslint-config/issues/978
- IMO, when there is an error from a shadow variable, it is usually visible during testing
- In other cases, it requires renaming "default" names such as `state` in Vuex, `event`, `callback`, `error` even when they aren't really used
- Not auto-fixable
- Also, it adds inconsistency in JS/TS, as this rule is only enabled in TS
=> fix(typescript): remove `@typescript-eslint/no-shadow`

lib/configs/codeStyle.ts, tests/fixtures/codestyle/input/objects.js, tests/fixtures/codestyle/output/objects.js
- Fix: https://github.com/nextcloud-libraries/eslint-config/issues/979
While it makes sense for large objects, requiring even small objects like `{ width, height }` be defined in 3+ lines.
I'd prefer to let developers decide when it is better.
```ts
function getPos(): { x: number, y: number } {
//
}
// vs
function getPos(): { 
x: number,
y: number,
} {
//
}
```
```ts
const { width, height } = getSize()
// vs
const { 
width,
height
} = getSize()
```
```ts
emit('app:config:change', { key, value })
// vs
emit('app:config:change', {
key,
value,
})
```
=> fix(codeStyle): allow devs write small objects in one line

lib/configs/vue.ts, lib/plugins/nextcloud-vue/index.ts, lib/plugins/nextcloud-vue/rules/index.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-exports.test.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-exports.ts, lib/plugins/nextcloud-vue/utils/lib-version-parser.test.ts, lib/plugins/nextcloud-vue/utils/lib-version-parser.ts
POC to see if we can handle deprecated parameters and practices in `nextcloud/vue@9.x.x`
TODO:
=> feat: introduce @nextcloud/vue eslint plugin

lib/configs/documentation.ts, tests/config-typescript.test.ts, tests/fixtures/JsdocJavascriptWithTypes.vue, tests/fixtures/JsdocJavascriptWithoutTypes.vue, tests/fixtures/JsdocTypescriptWithTypes.vue, tests/fixtures/JsdocTypescriptWithoutTypes.vue, tests/fixtures/typescript-vue-overrides.vue
- Fix: https://github.com/nextcloud-libraries/eslint-config/issues/980
- Currently `npm run lint` breaks many Vue + JS files if TS config is used
- `jsdoc/require-property-type` makes no harm in TS, there are no `@property`
- In `.vue` files (that can be both TS and JS):
- Use `jsdoc/no-types` only if there are TS types
- Use `jsdoc/require-param-type` only if there are no TS types
- Disable `jsdoc/require-returns-type` (because a return type is often inferred, not specified) 
- Allow type-tags in `jsdoc/check-tag-names` (because it can be used in a JS component)
So it **doesn't break** existing JS components (like before).
But it applies only ~half of JSDoc + TS rules in TS components.
Generate `files` on the fly by checking `<script lang>` to distinguish between JS and TS Vue files.
=> fix(documentation): do not remove JSDoc types in Vue JS files

lib/configs/vue.ts, lib/configs/vue3.ts
When using `<script setup>` we should directly use the modern approach using `defineOptions` also we should have a defined order so its easier to navigate in components.
@ShGKme as you are probably one of the heavy script-setup users, thats also the order in talk desktop right?
=> feat(vue3): add script-setup releated rules

CHANGELOG.md, README.md, build/format-changelog.mjs, package.json
This is already used by some other libraries and as you can see our changelog was already inconsistent, so this enforces a consistent layout.
=> build: add common changelog formatting and documentation for it

lib/plugins/nextcloud-vue/rules/no-deprecated-props.test.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-props.ts
Check more props
Found by looking at `@deprecated` at nextcloud-vue stable branch
Result for spreed repo (I was mostly migrating all props once they've been released)
=> fix(no-deprecated-props): extend existing rules to support other components

lib/configs/filesystem.ts
Noticed while linting.
If there's more known libraries to add (from what we're using), let me know
=> fix: ignore test report directories from linting

lib/configs/vue.ts
Allow using `RouterLink` without need to register it locally. Also make the pattern only allow the pascal case, as we already enforce pascal case component names.
=> fix(vue): also ignore the global router link component

lib/plugins/nextcloud-vue/rules/no-deprecated-exports.test.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-exports.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-props.test.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-props.ts
Require installed library version check before linting the file
Inspired by https://github.com/nextcloud-libraries/nextcloud-vue/pull/7032 - we should not force the rule or highlight the error, if component is not working correctly in this lib version
Other examples:
```js
const isAriaHiddenValid = versionSatisfies('8.2.0') // https://github.com/nextcloud-libraries/nextcloud-vue/pull/4835
const isDisableSwipeValid = versionSatisfies('8.23.0') // https://github.com/nextcloud-libraries/nextcloud-vue/pull/6452
const isVariantTypeValid = versionSatisfies('8.24.0') // https://github.com/nextcloud-libraries/nextcloud-vue/pull/6472
const isDefaultBooleanFalseValid = versionSatisfies('8.24.0') // https://github.com/nextcloud-libraries/nextcloud-vue/pull/6656
const isDateTimePickerFormatValid = …
```
=> fix(no-deprecated-props): respect nextcloud/vue library version for the rule

lib/plugins/l10n/rules/enforce-ellipsis.test.ts, lib/plugins/l10n/rules/enforce-ellipsis.ts
- also check `n` method
- use `CallExpression` for visitor (there are more Literals than call expressions, so this should boost performance).
=> fix(l10n-plugin): also check translation strings in `n` method

lib/configs/vue.ts, lib/plugins/l10n/index.ts, lib/plugins/l10n/rules/enforce-ellipsis-vue.test.ts, lib/plugins/l10n/rules/enforce-ellipsis-vue.ts, lib/plugins/l10n/rules/enforce-ellipsis.ts, lib/plugins/l10n/rules/index.ts, lib/plugins/l10n/rules/non-breaking-space-vue.test.ts, lib/plugins/l10n/rules/non-breaking-space-vue.ts, lib/plugins/l10n/rules/non-breaking-space.test.ts, lib/plugins/l10n/rules/non-breaking-space.ts
This also applies the rules to code inside Vue templates.
=> feat(l10n-plugin): also handle vue templates

CHANGELOG.md, package-lock.json, package.json
* fix(globs): adjust globs for test related files by @susnux in https://github.com/nextcloud-libraries/eslint-config/pull/1128
* fix(vue): use vue variant of `no-irregular-whitespace` by @susnux in https://github.com/nextcloud-libraries/eslint-config/pull/1129
* chore: lint this project as a library by @susnux in https://github.com/nextcloud-libraries/eslint-config/pull/1130
=> chore: prepare v9.0.0-rc.5

lib/plugins/nextcloud-vue/rules/no-deprecated-exports.test.ts, lib/plugins/nextcloud-vue/rules/no-deprecated-exports.ts
- All of them are not provided with Vue3 already, but should be a good indicator for Vue 2 to migrate
=> feat(nextcloud-vue-plugin): deprecate additional exports
